package com.decoutkhanqindev.custom_aod.presentation.theme.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp

// Token của màn AOD: xám thay vì trắng cho ít sáng, ít tốn pin, ít burn-in; màn này không bọc AodsTheme nên đọc giá trị mặc định của Local.
@Immutable
data class AodsClockTokens(
    val background: Color,
    val text: Color,
    val textMuted: Color,
    val textHint: Color,
    val control: Color,
    val controlDisabled: Color,
    val accent: Color,
    val digitalTimeSize: TextUnit,
    val stackedTimeSize: TextUnit,
    val dateSize: TextUnit,
    val bodySize: TextUnit,
    val detailSize: TextUnit,
    val captionSize: TextUnit,
    val analogSize: Dp,
    val analogMajorTickLength: Dp,
    val analogMinorTickLength: Dp,
    val analogMajorTickWidth: Dp,
    val analogMinorTickWidth: Dp,
    val analogHourHandWidth: Dp,
    val analogMinuteHandWidth: Dp,
    val analogCenterRadius: Dp,
    val iconSize: Dp,
    val smallIconSize: Dp,
    val mediaButtonSize: Dp,
    val mediaButtonPadding: Dp,
    val mediaButtonGap: Dp,
    val drawingSize: Dp,
    val eventTitleMaxWidth: Dp,
    val mediaTextMaxWidth: Dp,
    val textMaxWidth: Dp,
    val landscapeGap: Dp,
    val detailsTopPadding: Dp,
    val itemGap: Dp,
    val notificationIconsTopPadding: Dp,
    val notificationIconGap: Dp,
    val batteryTopPadding: Dp,
    val mediaTopPadding: Dp,
    val mediaRowTopPadding: Dp,
    val hintTopPadding: Dp,
    val lineGap: Dp,
    val inlineGap: Dp,
    val iconTextGap: Dp,
    val textGap: Dp,
    val edgeGlowWidth: Dp,
    val swipeThreshold: Dp,
    val imageAlpha: Float,
    val glowPulseMinAlpha: Float,
    val shiftDurationMillis: Int,
    val glowInDurationMillis: Int,
    val glowOutDurationMillis: Int,
    val glowPulseDurationMillis: Int,
    val hintFadeDurationMillis: Int,
)

val defaultAodsClock = AodsClockTokens(
    background = AodsPrimitiveColors.Black,
    text = AodsPrimitiveColors.Grey8A,
    textMuted = AodsPrimitiveColors.Grey6E,
    textHint = AodsPrimitiveColors.Grey5A,
    control = AodsPrimitiveColors.GreyB4,
    controlDisabled = AodsPrimitiveColors.Grey5A,
    accent = AodsPrimitiveColors.Mint,
    digitalTimeSize = AodsPrimitiveTypography.FontClock,
    stackedTimeSize = AodsPrimitiveTypography.FontClockStacked,
    dateSize = AodsPrimitiveTypography.FontLg,
    bodySize = AodsPrimitiveTypography.FontMd,
    detailSize = AodsPrimitiveTypography.FontSmPlus,
    captionSize = AodsPrimitiveTypography.FontSm,
    analogSize = 200.dp,
    analogMajorTickLength = AodsPrimitiveSpacing.Md,
    analogMinorTickLength = AodsPrimitiveSpacing.Sm,
    analogMajorTickWidth = AodsPrimitiveBorder.Thick,
    analogMinorTickWidth = AodsPrimitiveBorder.Medium,
    analogHourHandWidth = AodsPrimitiveSpacing.XsPlus,
    analogMinuteHandWidth = AodsPrimitiveBorder.Thick,
    analogCenterRadius = 5.dp,
    iconSize = AodsPrimitiveIconSize.SmPlus,
    smallIconSize = AodsPrimitiveIconSize.XsPlus,
    mediaButtonSize = AodsPrimitiveIconSize.Xl,
    mediaButtonPadding = AodsPrimitiveSpacing.Sm,
    mediaButtonGap = AodsPrimitiveSpacing.Lg,
    drawingSize = AodsPrimitiveIconSize.Enormous,
    eventTitleMaxWidth = 220.dp,
    mediaTextMaxWidth = 260.dp,
    textMaxWidth = 280.dp,
    landscapeGap = AodsPrimitiveSpacing.Xxl,
    detailsTopPadding = AodsPrimitiveSpacing.Sm,
    itemGap = AodsPrimitiveSpacing.Ms,
    notificationIconsTopPadding = AodsPrimitiveSpacing.Md,
    notificationIconGap = AodsPrimitiveSpacing.SmPlus,
    batteryTopPadding = AodsPrimitiveSpacing.MdPlus,
    mediaTopPadding = AodsPrimitiveSpacing.Lg,
    mediaRowTopPadding = AodsPrimitiveSpacing.Sm,
    hintTopPadding = AodsPrimitiveSpacing.LgPlus,
    lineGap = AodsPrimitiveSpacing.Xxs,
    inlineGap = AodsPrimitiveSpacing.Xs,
    iconTextGap = AodsPrimitiveSpacing.XsPlus,
    textGap = AodsPrimitiveSpacing.Sm,
    edgeGlowWidth = AodsPrimitiveSpacing.Lg,
    swipeThreshold = AodsPrimitiveSpacing.Giant,
    imageAlpha = AodsPrimitiveOpacity.Half,
    glowPulseMinAlpha = AodsPrimitiveOpacity.Faint,
    shiftDurationMillis = AodsPrimitiveMotion.Duration1500,
    glowInDurationMillis = AodsPrimitiveMotion.Duration400,
    glowOutDurationMillis = AodsPrimitiveMotion.Duration800,
    glowPulseDurationMillis = AodsPrimitiveMotion.Duration900,
    hintFadeDurationMillis = AodsPrimitiveMotion.Duration600,
)

val LocalAodsClock = staticCompositionLocalOf { defaultAodsClock }
